services:
  wordpress:
    build: .
    ports:
      - "31337:80"
    environment:
      WORDPRESS_DB_PASSWORD: password
      WORDPRESS_DB_HOST: mysql:3306
    volumes:
      - "wp:/var/www/html:rw"

  mysql:
    platform: linux/amd64
    image: "mysql:5.7"
    environment:
      MYSQL_ROOT_PASSWORD: password
    volumes:
      - db:/var/lib/mysql

  phpmyadmin:
    image: phpmyadmin/phpmyadmin:latest
    ports:
      - 31338:80
    environment:
      - PMA_ARBITRARY=1
      - PMA_HOST=mysql
    depends_on:
      - mysql

  wp-cli:
    image: "wordpress:cli-php7.1"
    depends_on:
      - "mysql"
      - "wordpress"
    volumes:
      - "wp:/var/www/html:rw"
      - "./bin/install-wp.sh:/usr/local/bin/install-wp:ro"
    entrypoint: ["/bin/sh", "-c", "/usr/local/bin/install-wp && sleep infinity"]

volumes:
  wp: {}
  db: {}
